apiVersion: apps/v1
kind: Deployment
metadata:
  name: bve-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bve-bvengine
  template:                 
    metadata:
      labels:
        app: bve-bvengine
    spec:
      containers:
        - name: bve-bvengine
          image: krishnatr/bve-bvengine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
